### PR TITLE
Add named vector support

### PR DESCRIPTION
**Pull request by fkchang**

### CODE REVIEW

**Comment by andreibondarev** [comment]
@fkchang You should be able to fix this with `standardrb --fix`.

**Comment by andreibondarev** [comment]
@fkchang Thank you for the PR!

**Comment by fkchang** [comment]
thanks for the gem - any thought on supporting the grpc api?

**Comment by andreibondarev** [comment]
> thanks for the gem - any thought on supporting the grpc api?

@fkchang I'm in favor of it, but I don't have time (or immediate needs) to focus on it. If you'd like to take the lead and develop it -- I'll make sure to help review, merge it, etc.

**Pull request merged**
